### ISSUE TITLE
Missing files for download

### ISSUE THREAD

**Issue by nongiga** [grp-bork/spire_contribute#15]
Hi there,

When I try to download the mags there is ~5% that give me Internal Server Error. I attached a list.
[spire_genomes_missing_urls.txt](https://github.com/user-attachments/files/16933681/spire_genomes_missing_urls.txt)
The rest of the downloads work perfectly. Could you solve this? 
![image](https://github.com/user-attachments/assets/a95b5602-3ceb-4eed-8af2-9714cf23a0ca)

**Comment by fullama** [comment]
Are you at Columbia university? Someone from there brought down our databases because of a crazy number of requests per second downloading every mag.

**Comment by fullama** [comment]
but you are right in the broken links - ill reply here when they are fixed - thanks for finding them

**Comment by fullama** [comment]
The issues should be fixed now.. everything that should be accessible now is.. 

If you are going to download them all though maybe dial it back a bit so it doesnt overload the server again.

Thanks!
A

FYI there was also a single file per study with the same mags on each study page - might be a bit late for that now though :-/
