### ISSUE TITLE
MAG cluster info

### ISSUE THREAD

**Issue by wwood** [grp-bork/spire_contribute#2]
Hi @fullama 

I downloaded the species representatives as per #1 but was confused why there are 107,078 `.fa.gz` files in it, when the manuscripts says

>these novel MAGs form 92 134 novel species-level clusters

Also, I wasn't sure in the `spire_v1_genome_metadata.tsv.gz` file how to know which MAG was chosen as the representative. The downstream impact of that is I'm not sure what the checkm2 stats are of the rep MAGs, since that information doesn't appear in `spire_v1_cluster_metadata.tsv.gz`.

TIA, ben

**Comment by wwood** [comment]
Also, relatedly, why does the `spire_v1_cluster_metadata.tsv.gz` file have 133402 lines in it? All IDs seem to be unique.

**Comment by fullama** [comment]
I was going to put a note in the download section of the website with an explanation :D 

So we have 2 resources: [progenomes](https://progenomes.embl.de/index.cgi) (isolates) and spire (mags).
 - I analysed all the mags in spire together with all the genomes in progenomes. 
 - For spire clusters that we could link to a progenomes genome it was selected as the representative.
   - ~90 thousand are clusters that dont overlap with progenomes
   - ~14 thousand had an overlap with progenomes
   - ~26 thousand clusters in progenomes with no overlap in spire

so.. the (~90T) novel clusters we refer to were the ones that we didn't link to progenomes, the representative file i created was all 90T along with the 14T that are the representative of the "non-novel": clusters, and the 133T in the cluster_metadata file are all reps from spire and progenomes.

the clusters/representatives that are from progenomes are the ones that start with specI.
I will try update the documentation to make these points clear from the webpage - thanks for the feedback though - just apologies it wasnt clear.

i can also add the name of the representative genomes to that file.

**Comment by fullama** [comment]
I added a mapping of cluster to representative genome to the download section

let me know if you come across any further friction or issues!
