### ISSUE TITLE
Missing assemblies

### ISSUE THREAD

**Issue by snayfach** [grp-bork/spire_contribute#6]
For some studies, the link to download the assemblies .tar file is broken:

> Larson_2022_elderly
> Panwar_2020_lake_Antarctica
> Cao_2023_goat
> Bell_2018_groundwater
> McKay_2021_coalbed
> Castro-Nallar_2023_Patagonia_fjords
> Wang_2022_elderly_osteoporosis
> Fujimoto_2021_FMT_rCDI
> Zhong_2023_virus_Arctic
> Liang_2020_adenomatous_polyps
> PRJNA309119_Eurytemora_copepod_water
> Aylward_2012_ant_fungus

For example:
`wget https://swifter.embl.de/~fullam/spire/compiled/Aylward_2012_ant_fungus_spire_v1_assemblies.tar`

> --2023-12-26 23:17:13--  https://swifter.embl.de/~fullam/spire/compiled/Aylward_2012_ant_fungus_spire_v1_assemblies.tar
> Resolving swifter.embl.de (swifter.embl.de)... 194.94.44.56
> Connecting to swifter.embl.de (swifter.embl.de)|194.94.44.56|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2023-12-26 23:17:14 ERROR 404: Not Found.

For other studies, the link is fine, but there are missing assemblies from the tarball. Here's one example:
```
wget https://swifter.embl.de/~fullam/spire/compiled/Avila-Herrera_2020_astronaut_ISS_spire_v1_assemblies.tar
tar -xvf Avila-Herrera_2020_astronaut_ISS_spire_v1_assemblies.tar
ls Avila-Herrera_2020_astronaut_ISS | grep SAMN10252997
```

Overall there are 3660 samples between these two categories

**Comment by snayfach** [comment]
There are also studies where the tarball is empty. Here's one example: https://spire.embl.de/study/Boktor_2022_PD_RUMC?page=1

And here's the full list:

> Boktor_2022_PD_RUMC
> Boktor_2022_PD_TBC
> Bowerman_2021_rodent
> Derosa_2022_NSCLC
> Ekwanzala_2020_wastewater
> Haifer_2022_FMT_donors
> Jo_2022_PD
> Kim_2021_Korea
> Lee_2022_melanoma
> Leung_2022_liver_NAFLD
> Liu_2022_CRC_China
> Mao_2022_PD
> Matson_2018_melanoma
> McCulloch_2022_melanoma
> Peters_2019_melanoma
> Pleasure-Ateba_2020_dog
> Podlesny_2022_FMT_UC
> Qian_2020_PD
> Riquelme_2021_wastewater
> Routy_2018_PD1
> Thomas_2019_CRC_Italy
> Wallen_2022_PD

**Comment by fullama** [comment]
Thanks for the detailed report!
The tar file permissions should all be fixed now.. the missing assemblies in the tars are most likely one that failed to assemble - i will add that to the list of changes to make to the site so these samples are flagged.

The studies where the tarball was empty i have removed from the site as they were mistakenly labelled as ready for release.
