### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by akques** [grp-bork/spire_contribute#8]
Hello! Thank you for your work. I've encountered a couple of issues while use SPIRE to  explore data from taxonomy and would appreciate some help. 

1. Firstly, ,I'd like to know if there's a way to **download data for the entire genus at once**, instead of having to download data for each SPIRE ID individually. The current process can be cumbersome when dealing with **a large number of samples.** 
2. Secondly, Error with download links: When attempting to download data using the "Download MAG" or "Download Assemble..." links, I encounter an **"Internal Server Error."** I'm uncertain if this is a network issue or another reason.

I hope to receive some guidance on resolving these issues. Thank you!

**Comment by akques** [comment]
I have downloaded spire_v1_genome_metadata.tsv,by using  like `wget http://spire.embl.de/download_file/${genome_id}`,but I also want to know about these document meaning ?

1.Cluster Metadata: include **rep both** pg3 and SPIRE?
2.Genome Metadata: include **only SPIRE MAGs** spire_id 

So,if I want to download all sequence from both pg3 and SPIRE ,I have to sepreate download MAGs inSPIRE , isolates and MAGs in pg3?

**Comment by akques** [comment]
I also want to ask about the Microntology ,I downloaded it and  found it not include all data ,and it has many repetitive data ,I wonder why ?
![image](https://github.com/grp-bork/spire_contribute/assets/151001372/31c6b4a6-c977-47a4-9997-1024ce19e1eb)

**Comment by akques** [comment]
I am seeking an easier way to download the entire database. In your paper, you mentioned, 'SPIRE encompasses 99,146 metagenomic samples from **739** studies, covering a wide array of microbial environments, and is augmented with manually curated contextual data.' However, on the website, I only found information about **719** studies. Could you please explain this discrepancy? The website I am referring to is http://spire.embl.de/environment." I have attached the genome ID,and download with wget, but I would greatly appreciate a list of all MD5 checksums to verify my downloads.

**Comment by fullama** [comment]
> Hello! Thank you for your work. I've encountered a couple of issues while use SPIRE to explore data from taxonomy and would appreciate some help.
> 
> 1. Firstly, ,I'd like to know if there's a way to **download data for the entire genus at once**, instead of having to download data for each SPIRE ID individually. The current process can be cumbersome when dealing with **a large number of samples.**
> 2. Secondly, Error with download links: When attempting to download data using the "Download MAG" or "Download Assemble..." links, I encounter an **"Internal Server Error."** I'm uncertain if this is a network issue or another reason.
> 
> I hope to receive some guidance on resolving these issues. Thank you!

1. Unfortunately not right now.. its a technical limitation but we have plans to overcome this.
2. This may have bee bad timing as our filesystem underwent an upgrade, if you have any specific examples of links that are consistently broken d o let me know and i can investigate.

**Comment by fullama** [comment]
> I have downloaded spire_v1_genome_metadata.tsv,by using like `wget http://spire.embl.de/download_file/${genome_id}`,but I also want to know about these document meaning ?
> 
> 1.Cluster Metadata: include **rep both** pg3 and SPIRE? 2.Genome Metadata: include **only SPIRE MAGs** spire_id
> 
> So,if I want to download all sequence from both pg3 and SPIRE ,I have to sepreate download MAGs inSPIRE , isolates and MAGs in pg3?

Yes

**Comment by fullama** [comment]
> I also want to ask about the Microntology ,I downloaded it and found it not include all data ,and it has many repetitive data ,I wonder why ? ![image](https://private-user-images.githubusercontent.com/151001372/298509078-31c6b4a6-c977-47a4-9997-1024ce19e1eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MzY0NjksIm5iZiI6MTcwNjUzNjE2OSwicGF0aCI6Ii8xNTEwMDEzNzIvMjk4NTA5MDc4LTMxYzZiNGE2LWM5NzctNDdhNC05OTk3LTEwMjRjZTE5ZTFlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQxMzQ5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZWIyY2E3YzhkOWJkMjE2MzE0Mjc0ZGVkY2YwZGRjZTJhZGRkOTAyNTI0ZDg2MDVjNzIyNDQ3OTUyYzRhZmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F1qPDQSF5ruwOdjW-3qyI391TIcXIIf-viMO9sb-X6I)

this was fixed here: https://github.com/grp-bork/spire_contribute/issues/9

**Comment by fullama** [comment]
> I am seeking an easier way to download the entire database. In your paper, you mentioned, 'SPIRE encompasses 99,146 metagenomic samples from **739** studies, covering a wide array of microbial environments, and is augmented with manually curated contextual data.' However, on the website, I only found information about **719** studies. Could you please explain this discrepancy? The website I am referring to is http://spire.embl.de/environment." I have attached the genome ID,and download with wget, but I would greatly appreciate a list of all MD5 checksums to verify my downloads.

I took some studies down temporarily as some files seemed incomplete.. i will put these back when i have verified all is correct

our plans for making the data easier to download should also come with md5s.. but i willl lookinto another solution that i could maybe provide in the meantime.
