### ISSUE TITLE
microntology and habitat 

### ISSUE THREAD

**Issue by akques** [grp-bork/spire_contribute#9]
Hi, I have downloaded the [Microntology](https://swifter.embl.de/~fullam/spire/metadata/spire_v1_microntology.tsv.gz). 

Firstly, I noticed some data repetition. I'm not sure why this happened; an explanation would be helpful! I deleted the repetitive entries and created a new file with 268,605 rows.
![image](https://github.com/grp-bork/spire_contribute/assets/151001372/5a840918-8045-48b6-8bf8-cf153b015456)

However, I have observed that some information appears incomplete. For instance, your determination of 92 terms to describe microbial habitats and lifestyles is often represented as simple phrases like 'host-associated:animal.'
![image](https://github.com/grp-bork/spire_contribute/assets/151001372/e4850aeb-473a-4857-b030-e8b8de5346b8)

Perhaps supplementing the data with more specific details, as mentioned in your paper, such as 'host-associated:animal host:mammalian host:human,' would provide greater specificity? 
![image](https://github.com/grp-bork/spire_contribute/assets/151001372/9cdbd9d0-11a5-40c4-8463-184588644688)

for me ,and similar to others in https://github.com/grp-bork/spire_contribute/issues/4 , not only the 92 tags but also a list of genomes by the study and detailed habitat information would be very helpful!

**Comment by fullama** [comment]
sorry about that.. the ends of the longer micontologies got cut off the last time the file was updated.. i have fixed the file and it should be ok now.. let me know if you see any further issues!
